#!/bin/bash
set -e
cd ~/growvibe
gen() { openssl rand -base64 32 | tr -d '\n=/+' | head -c 40; }
ADMIN_TOKEN=$(gen)
SESSION_SECRET=$(gen)
MINIO_SECRET_KEY=$(gen)
POSTGRES_PASSWORD=$(gen)
WHATSAPP_VERIFY=$(gen)

cat > .env <<ENVEOF
POSTGRES_DB=growvibe
POSTGRES_USER=growvibe
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_PORT=5432

API_PORT=4000
WEB_PORT=5173
ADMIN_PORT=5174

ADMIN_TOKEN=$ADMIN_TOKEN
ADMIN_USERNAME=admin
ADMIN_PASSWORD=FNXMD12345
SESSION_SECRET=$SESSION_SECRET

PUBLIC_BASE_URL=http://213.155.23.46:4000
VITE_API_URL=http://213.155.23.46:4000
CORS_ORIGINS=http://213.155.23.46:5173,http://213.155.23.46:5174,http://localhost:5173,http://localhost:5174

KASPI_PHONE=+7 (700) 000-00-00
KASPI_AMOUNT=50000

STORAGE_DRIVER=minio
MINIO_PORT=9000
MINIO_CONSOLE_PORT=9001
MINIO_ACCESS_KEY=growvibe
MINIO_SECRET_KEY=$MINIO_SECRET_KEY
MINIO_BUCKET=receipts

WHATSAPP_ACCESS_TOKEN=
WHATSAPP_PHONE_NUMBER_ID=
WHATSAPP_WEBHOOK_VERIFY_TOKEN=$WHATSAPP_VERIFY
WHATSAPP_GRAPH_VERSION=v24.0
WHATSAPP_TEMPLATE_APPLICATION_RECEIVED=
WHATSAPP_TEMPLATE_PROOF_RECEIVED=
WHATSAPP_TEMPLATE_PAYMENT_VERIFIED=
WHATSAPP_TEMPLATE_REMINDER_24H=
WHATSAPP_TEMPLATE_REMINDER_3H=
ENVEOF
chmod 600 .env

echo "OK: .env created"
echo "ADMIN_TOKEN len: ${#ADMIN_TOKEN}"
echo "SESSION_SECRET len: ${#SESSION_SECRET}"
echo "MINIO_SECRET_KEY len: ${#MINIO_SECRET_KEY}"
echo "POSTGRES_PASSWORD len: ${#POSTGRES_PASSWORD}"
echo "--- non-secret vars ---"
grep -E '^(POSTGRES_DB|POSTGRES_USER|ADMIN_USERNAME|PUBLIC_BASE_URL|VITE_API_URL|CORS_ORIGINS|KASPI_|STORAGE_|MINIO_BUCKET|MINIO_ACCESS_KEY)' .env
